services:


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: mydatabase

  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  

  proxy:
    build: proxy
    ports:
      - 8083:81
    depends_on:
      - backend
volumes:
  pgdata:
  mongodbdata:

