services:
  backend:
    build: backend
    secrets:
      - db-password
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: mydatabase

  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  

  proxy:
    build: proxy
    ports:
      - 8083:81
    depends_on:
      - backend
volumes:
  db-data:
  pgdata:
  mongodbdata:
secrets:
  db-password:
    file: db/password.txt