@app_HostAddress = http://localhost:80/api/products

POST http://localhost:80/api/products
Content-Type: application/json
Accept: application/json

{
  "title": "New Produc2t12",
  "price": 99.99,
  "description": "A marvelous prod22uct",
  "category": "Others",
  "image": "https://example.com/image.jpg",
  "rating": {
    "rate": 4.7,
    "count": 15
  }
}

###
PUT  http://localhost/api/products/1
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "title": "Updated Product Title atualizado",
  "price": 150.00,
  "description": "Updated desWcription",
  "category": "New Category",
  "image": "https://example.com/new-image.jpg",
  "rating": {
    "rate": 4.9,
    "count": 20
  }
}

###
GET http://localhost:80/api/products/1
Content-Type: application/json
Accept: application/json
###
GET http://localhost:80/api/products?_page=1&_size=10&_order=price desc,title asc
Content-Type: application/json
Accept: application/json
###

###

GET http://localhost:80/api/products/categories
###
GET http://localhost:80/api/products/category/Others
###
DELETE  http://localhost:80/api/products/1

Content-Type: application/json
Accept: application/json

###
POST http://localhost/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe",
  "password": "password123"
}


###
GET http://localhost/hello/public
Content-Type: application/json
Accept: application/json

###

GET http://localhost/hello/protected
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJqb2huX2RvZSIsIm5iZiI6MTc1MzAyMDczNCwiZXhwIjoxNzUzMDI0MzM0LCJpYXQiOjE3NTMwMjA3MzQsImlzcyI6Ik15QXBpSXNzdWVyIiwiYXVkIjoiTXlBcGlBdWRpZW5jZSJ9.ija6jUtRsLhlk39y5HzV5Pju1Ye03alDTEvNtTZ3Sic
###

GET http://localhost/hello/protected
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJqb2huX2RvZSIsIm5iZiI6MTc1MzAyMDU2MCwiZXhwIjoxNzUzMDI0MTYwLCJpYXQiOjE3NTMwMjA1NjAsImF1ZCI6Ik15QXBpQXVkaWVuY2UifQ.wMA-mEwUMixd2Swk7LpgQN49pFKAP2t0O7dVPy43Evc

###

GET http://localhost:80/api/carts?_page=1&_size=10&_order=id desc,userId asc
Content-Type: application/json
Accept: application/json

###
POST http://localhost:80/api/cart
Content-Type: application/json
Accept: application/json

{
    
  "date": "2025-07-19",
  "products": [
{
  "id": 6,
  "title": "Updated Product Title atualizado",
  "price": 150.00,
  "description": "Updated desWcription",
  "category": "New Category",
  "image": "https://example.com/new-image.jpg",
  "rating": {
    "rate": 4.9,
    "count": 20
  }
}
  ]
}

###
GET http://localhost:80/api/cart?_page=1&_size=10&_order=date asc

###
GET http://localhost:80/api/cart/8
###

PUT http://localhost:80/api/cart/18
Content-Type: application/json
Accept: application/json


{
    "id": 18,
  "date": "2025-07-19",
  "products": [
{
  "id": 6,
  "title": "Updated Product Tsitle atualizado",
  "price": 150.00,
  "description": "Updated desWcription",
  "category": "New Category",
  "image": "https://example.com/new-image.jpg",
  "rating": {
    "rate": 4.9,
    "count": 20
  }
}
  ]
}

###
DELETE http://localhost:80/api/cart/6

{
  "message": "Cart deleted successfully"
}

####
POST http://localhost:80/api/users
Content-Type: application/json
Accept: application/json

{
  "email": "john@example.com",
  "username": "john_doe",
  "password": "password123",
  "name": {
    "firstname": "John",
    "lastname": "Doe"
  },
  "address": {
    "city": "CityX",
    "street": "Main St",
    "number": 100,
    "zipcode": "12345",
    "geolocation": {
      "lat": "0.00",
      "long": "0.00"
    }
  },
  "phone": "555-0000",
  
  "status": "Active",
  "role": "Customer"
}

###
PUT http://localhost:80/api/users/1
Content-Type: application/json
Accept: application/json

{
    "id": 1,
  "email": "john@example.com",
  "username": "john_doe",
  "password": "password123",
  "name": {
    "firstname": "John",
    "lastname": "Doe"
  },
  "address": {
    "city": "CityX",
    "street": "Main St",
    "number": 100,
    "zipcode": "12345",
    "geolocation": {
      "lat": "0.00",
      "long": "0.00"
    }
  },
  "phone": "555-0000",
  
  "status": "Active",
  "role": "Customer"
}

####
GET http://localhost:80/api/users/1


###
GET http://localhost:80/api/users?_page=1&_size=10&_order=username asc

###
DELETE http://localhost:80/api/users/1